### ISSUE TITLE
Correct the data insertion to csv file

### ISSUE THREAD

**Issue by pushp1997** [pushp1997/Amazon-Product-Reviews-Scraping#2]
Desired:
| Serial No | Name | Ratings | Title | Date | Text |
| --- | --- | --- | --- | --- | --- |
| 1 | Govinda Dasa | 5.0 | The Saviour of the Brand | 7 June 2019 | It is a known fact that many people are disapp...

Current:

First all the Names are getting inserted than all the ratings, and so on

**Comment by falguni-k** [comment]
Hello. How did you access Amazon DB. I am not able to access it.

**Comment by pushp1997** [comment]
Hey @falguni-k thank you for your interest, I am not accessing Amazon Db in the entire script, it is scraping the data from the Amazon website and then storing it in a csv file. Let me know if you have more doubts.

**Comment by selamanse** [comment]
@falguni-k are you still on this // can I help?

**Comment by falguni-k** [comment]
@selamanse please continue. Thanks

**Comment by pushp1997** [comment]
Hi @falguni-k @selamanse, thanks for your interest, is any of you working on this issue?

**Comment by selamanse** [comment]
@pushp1997 I would like to try if you assign me

**Comment by selamanse** [comment]
Hi @pushp1997 can you please have a look at my pr? thx
